#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-modelo-deployment
spec:
  selector:
    matchLabels:
      app: movie-modelo
  replicas: 1
  template:
    metadata:
      labels:
        app: movie-modelo
    spec:
      containers:
      - name: mi-contenedor
        image: docker.io/zurisaddairj/fastapimovie:latest
        ports:
        - containerPort: 80

      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: movie-modelo
  name: movie-modelo
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: movie-modelo
  type: LoadBalancer